### PR TITLE
[#7] Updated Semester Dates

### LINKED ISSUE #7: RITWeek doesn't recognize Intersession/Other Incorrect Semester Dates
As of `1/15/2016`, viewing [RITWeek](https://whatweekisit.rit.lol/) displays the following:
image

I think this is due to the following line in [whatweekisit.js](https://github.com/corbanmailloux/RITWeek/blob/gh-pages/js/whatweekisit.js#L65):
`var interTigerStartDate = moment("2015-01-04"); // Intersession TigerTerm`
The TigerTerm started this January in **2016**, not **2015**.

Likewise, the [spring start date](https://github.com/corbanmailloux/RITWeek/blob/gh-pages/js/whatweekisit.js#L66) has the wrong month (**12** instead of **1**) and the [summer start date](https://github.com/corbanmailloux/RITWeek/blob/gh-pages/js/whatweekisit.js#L68) appears to be bad copypasta (`var summerTigerStartDate = moment("2015-01-04"); // Summer TigerTerm (10-week)`).

### PR DESCRIPTION
**Pull request by valbooth28**
#### Changes:
- Fixed `interTigerStartDate`, `springStartDate` and `summerTigerStartDate` to match [RIT's Academic Calendar](https://inside.cias.rit.edu/wordpress/wp-content/uploads/2013/04/2015-16-calendar-approved.pdf). 
- Added check to `getWeek()`, since moment.js's isBetween() is [exclusive](http://stackoverflow.com/a/29495647). **Note:** left the `isBetween()` call there (as opposed to refactoring for inclusive checking with less `||` statements) because there's currently a [proposal](https://github.com/moment/moment/issues/2164) to make it inclusive. I only make it inclusive with the start date, since many of the terms seems to overlap. I feel like this makes the most sense from a high level.
#### Testing Considerations:
- [x] UI functions as before. Since I wasn't able to get the css/bootstrap working locally, I can't confirm if it works the same or not. Since there's only `js` changes the UI shouldn't change, but it can't hurt to check.
- [x] On January 25th somebody should go around and double check that it says that it's week 1 at RIT.
#### Deployment Considerations:

None.

### CODE REVIEW

File: js/whatweekisit.js [hunk 1]
```diff
@@ -20,7 +20,13 @@ function storageAvailable(type) {
 function getWeek() {
     nowMoment = moment();
     for (var i = 0; i < weeks.length; i++) {
-        if (nowMoment.isBetween(weeks[i].beginning, weeks[i].end, "day")) {
+        var beginning = weeks[i].beginning;
+        var end = weeks[i].end;
+        //Note: isBetween() is exclusive. This could be done with less || statements,
+        //but I left the isBetween() call in case it is one day inclusive. -VB 1/15/16
+        var withinWeek = nowMoment.isBetween(beginning, end, "day");
+        withinWeek = withinWeek || nowMoment.isSame(beginning) || nowMoment.isSame(end);
```
Comment (valbooth28) [inline js/whatweekisit.js]: I created the `withinWeek` variable because I wasn't sure how picky you were with code style, and it was going to be a really long line if I didn't make a variable/split it into two lines. Feel free to recombine if you don't care.

File: js/whatweekisit.js [hunk 2]
```diff
@@ -20,7 +20,13 @@ function storageAvailable(type) {
 function getWeek() {
     nowMoment = moment();
     for (var i = 0; i < weeks.length; i++) {
-        if (nowMoment.isBetween(weeks[i].beginning, weeks[i].end, "day")) {
+        var beginning = weeks[i].beginning;
+        var end = weeks[i].end;
+        //Note: isBetween() is exclusive. This could be done with less || statements,
+        //but I left the isBetween() call in case it is one day inclusive. -VB 1/15/16
+        var withinWeek = nowMoment.isBetween(beginning, end, "day");
+        withinWeek = withinWeek || nowMoment.isSame(beginning);
```
Comment (valbooth28) [inline js/whatweekisit.js:28]: I created the `withinWeek` variable because I wasn't sure how picky you were with code style, and it was going to be a really long line if I didn't make a variable/split it into two lines. Feel free to recombine if you don't care.

File: js/whatweekisit.js [hunk 3]
```diff
@@ -248,3 +253,11 @@ function maggie (pineapple) {
     return ("Joules");
 } // badumshpuh
 */
+
+
+// For Adam -VB
+/*
+    function areThereItaliansInCanada(){
```
Comment (corbanmailloux) [inline js/whatweekisit.js:260]: Of course there aren't!
Silly Adam...

**Comment by corbanmailloux** [comment]
I'll take a look at this tonight and merge it in. 

I'm not sure how I messed the dates up that badly. This is why I shouldn't code while sleepy.

**Comment by corbanmailloux** [comment]
2 notes:
- I'm merging this before the 25th because it works for intersession, so it should work for spring. I will come back and check.
- Normally, I would have made this two PRs; one for the date fix, and one for the exclusive/inclusive `isBetween()` calls. Obviously not a big deal in this repo.

Thanks, @valbooth28 for the fixes. I don't know how I messed up the dates so badly.
